config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :selections
  end

  resource :sessions, only: [:new, :create, :destroy]
  resources :leaderboard
  resource :welcome, only: [:index]

  root 'welcome#index'

end

app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  include Mongoid::Paperclip

   def self.after_commit(*args, &block)
     args.each do |arg|
     case arg[:on]
       when :destroy
         after_destroy &block
       end
     end
   end

  has_mongoid_attached_file :picture,
   :styles => {
      :thumb => "100x100#",   # Centrally cropped
      :small  => "150x150>"}  # Only squish if it's larger than this

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  def password
  	@password
  end

  def password=(new_password)
  	@password = new_password
  	self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
  	if BCrypt::Password.new(self.password_digest) == test_password
  		self
  	else
  		false
  	end
  end

   has_many :selections

   validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Sign up successful"
      session[:remember_token] = @user.id.to_s
      redirect_to leaderboard_index_path
    else
      flash[:danger] = "Sign up failed, try again"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user = User.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to :root
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :picture)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<h1>Edit User</h1>
	<%= form_for (@user) do |f| %>
		Name: <%= f.text_field :name %>
		Email: <%= f.text_field :email %>
		<p>Upload a photo: <%= f.file_field :picture %></p>
		<%= f.submit %>

	<% end %>

</div>

app/views/users/index.html.erb
<div class="container">
<h1>Fantasy League Members</h1>

<% @users.each do |u| %>
<blockquote>
	<p><%= u.name %></p>
	<p><%= link_to "view profile", user_path(u) %></p>
</blockquote>
<% end %>

</div>

app/views/users/new.html.erb
<div class="container">
<h2>Create an account:</h2>

<%= form_for @user do |f| %>
<%= f.text_field :name, placeholder: "Username" %>
<%= f.text_field :email, placeholder: "Email address" %>
<%= f.password_field :password, placeholder: "Password" %>
<p>Upload a photo: <%= f.file_field :picture %></p>
<%= f.submit "Sign me up!" %>
<% end %>

<br />
<p>Already have an account? <%= link_to "Sign in here", new_sessions_path %></p>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1><%= @user.name %>'s Profile</h1>
	<blockquote>
		<p><%= image_tag @user.picture.url(:thumb) %></p>
		<p>Username: <%= @user.name %></p>
		<p>Email: <%= @user.email %></p>
	</blockquote>

	<% if @user.selections.length > 0 %>
	<div class="btn-group">
		<% @user.selections.each do |s| %>
		<ul>
			<li>My Baseball Team: <%= s.baseball_team %></li>
			<li>My Football Team: <%= s.football_team %></li>
			<li>My Basketball Team: <%= s.basketball_team %></li>
			<li>My Hockey Team: <%= s.hockey_team %></li>
		</ul>
			<% if @user == current_user %>
			<p><%= link_to "Edit my Selections", edit_user_selection_path(@user, s), class: 'btn btn-warning btn-sm' %>
			<%= link_to "Delete my Selections", [@user, s], {method: :delete, class: 'btn btn-danger btn-sm'} %></p>
			<% end %>
		<% end %>
	</div>
	<% else %>
	<p><b><%= @user.name %></b> has not created their Fantasy Life yet :(</p>
	<% end %>

	<div class="row">		
			<% if @user == current_user %>
				<% if @user.selections.length == 0 %>
					<%= link_to "Add Selections", new_user_selection_path(@user), class: 'btn btn-primary btn-lg' %>
				<% end %>
			<% end %>
			<%#= link_to "Edit User", edit_user_path(@user.id), class: 'btn btn-warning btn-lg' %> 
			<%#	= link_to "Delete User", {action: "destroy", id:@user}, {method: :delete, data:{confirm: "Are you sure you want to delete this user?"}, class: 'btn btn-danger btn-lg'} %>
			
		
		
	</div>
</div>