config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :selections
  end

  resource :sessions, only: [:new, :create, :destroy]
  resources :leaderboard
  resource :welcome, only: [:index]

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyLife</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fantasy Life</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if !current_user %>
        <li class="navbar-text navbar-right">Sign in to see leaderboard</li>
        <% else %>
        <li><%= link_to "Leaderboard", leaderboard_index_path %></li>
        <% end %> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>     
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_sessions_path %></li>
        	<% else %>
          <li class="navbar-text navbar-right"><span>Hello, <%= link_to current_user.name, user_path(current_user) %></span></li>
          <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %> 
      </ul> 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- this tells the rails app where to display the flash messages -->
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>

</body>
</html>